import { withSecurity } from '../_lib/middleware.js'
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
} from 'docx'

// Parse inline markdown (bold, code) into an array of TextRun
function inlineRuns(text) {
  const runs = []
  const parts = text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g)
  for (const part of parts) {
    if (!part) continue
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true }))
    } else if (part.startsWith('`') && part.endsWith('`')) {
      runs.push(new TextRun({ text: part.slice(1, -1), font: 'Courier New', size: 18 }))
    } else {
      runs.push(new TextRun({ text: part }))
    }
  }
  return runs.length ? runs : [new TextRun({ text: text })]
}

function contentToParagraphs(content) {
  if (!content) return []
  const paragraphs = []
  const lines = content.split('\n')
  let inCode = false
  const codeLines = []

  for (const line of lines) {
    if (line.startsWith('```')) {
      if (inCode) {
        paragraphs.push(new Paragraph({
          children: [new TextRun({ text: codeLines.join('\n'), font: 'Courier New', size: 18 })],
          indent: { left: 360 },
        }))
        codeLines.length = 0
        inCode = false
      } else {
        inCode = true
      }
      continue
    }
    if (inCode) { codeLines.push(line); continue }

    if (!line.trim()) { paragraphs.push(new Paragraph({ text: '' })); continue }

    // Headings
    const hm = line.match(/^(#{1,6})\s+(.+)/)
    if (hm) {
      const levels = [
        HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3,
        HeadingLevel.HEADING_4, HeadingLevel.HEADING_5, HeadingLevel.HEADING_6,
      ]
      paragraphs.push(new Paragraph({ text: hm[2], heading: levels[hm[1].length - 1] }))
      continue
    }

    // Checkbox
    const cbm = line.match(/^(\s*)- \[([ xX])\] (.+)/)
    if (cbm) {
      const checked = cbm[2].toLowerCase() === 'x'
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text: checked ? '☑ ' : '☐ ' }), ...inlineRuns(cbm[3])],
        indent: { left: cbm[1].length * 180 + 360 },
      }))
      continue
    }

    // Bullet
    const bm = line.match(/^(\s*)[-*]\s+(.+)/)
    if (bm) {
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text: '• ' }), ...inlineRuns(bm[2])],
        indent: { left: bm[1].length * 180 + 360 },
      }))
      continue
    }

    // Numbered list
    const nm = line.match(/^(\s*)(\d+)\.\s+(.+)/)
    if (nm) {
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text: `${nm[2]}. ` }), ...inlineRuns(nm[3])],
        indent: { left: nm[1].length * 180 + 360 },
      }))
      continue
    }

    // Table row — render as plain text row (full table API is complex)
    if (line.startsWith('|')) {
      const cells = line.split('|').filter((_, i, a) => i > 0 && i < a.length - 1).map(c => c.trim())
      if (cells.every(c => /^[-:]+$/.test(c))) continue // separator row
      paragraphs.push(new Paragraph({
        children: cells.flatMap((c, i) => [
          ...(i > 0 ? [new TextRun({ text: '  |  ' })] : []),
          ...inlineRuns(c),
        ]),
      }))
      continue
    }

    paragraphs.push(new Paragraph({ children: inlineRuns(line) }))
  }

  return paragraphs
}

function buildDocx(schema_data) {
  const children = []

  children.push(
    new Paragraph({
      text: schema_data.title ?? 'Untitled Document',
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({ text: '' }),
  )

  for (const section of schema_data.sections ?? []) {
    if (section.heading) {
      children.push(
        new Paragraph({ text: section.heading, heading: HeadingLevel.HEADING_1, pageBreakBefore: children.length > 2 }),
      )
    }
    if (section.content) children.push(...contentToParagraphs(section.content))

    for (const sub of section.subsections ?? []) {
      if (sub.heading) children.push(new Paragraph({ text: sub.heading, heading: HeadingLevel.HEADING_2 }))
      if (sub.content) children.push(...contentToParagraphs(sub.content))
      children.push(new Paragraph({ text: '' }))
    }

    if (!section.subsections?.length) children.push(new Paragraph({ text: '' }))
  }

  return new Document({
    creator: 'WWT Ops Hub',
    title: schema_data.title ?? 'Document',
    description: 'Generated by WWT Ops Hub DocGen',
    sections: [{ children }],
  })
}

async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ message: 'Method not allowed' })

  const { schema_data, title = 'document' } = req.body ?? {}
  if (!schema_data) return res.status(400).json({ message: 'schema_data is required' })

  try {
    const doc = buildDocx(schema_data)
    const buffer = await Packer.toBuffer(doc)
    const safe = (title ?? 'document').replace(/[^a-z0-9_\-. ]/gi, '_').trim().slice(0, 60) || 'document'
    const filename = `${safe}.docx`

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
    res.setHeader('Content-Length', buffer.byteLength)
    return res.end(Buffer.from(buffer))
  } catch (err) {
    console.error('[docgen/download] Error:', err)
    return res.status(500).json({ message: err.message ?? 'DOCX generation failed' })
  }
}

export default withSecurity(handler)
